#!/usr/bin/env bash
set -Eeuo pipefail

###############################################################################
# build_oe4t_jetson_multi_platform_v67.sh
#
# v67 release launcher for build_oe4t_jetson_multi_platform_v65.sh.
#
# This release preserves the v65 source and creates a patched v67 runtime copy
# under .jetson-builder-v67-runtime before executing it. It does not overwrite
# v65. The v67 patch completes the Thor tegra-flashtools native wrapper by wrapping
# both the tegra-flash subdirectory helpers and the direct PATH helpers, because Thor do_image_ext4 now fails
# when the native image-generation task executes NVIDIA's foreign-architecture
# mksparse payload directly:
#
#   mksparse: Exec format error
#
# Usage is unchanged from v65:
#   TARGET_PLATFORM=thor ./build_oe4t_jetson_multi_platform_v67.sh
#   TARGET_PLATFORM=thor ./build_oe4t_jetson_multi_platform_v67.sh --bundle
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_SCRIPT="${JETSON_BUILDER_V65_SCRIPT:-$SCRIPT_DIR/build_oe4t_jetson_multi_platform_v65.sh}"
RUNTIME_DIR="$SCRIPT_DIR/.jetson-builder-v67-runtime"
RUNTIME_SCRIPT="$RUNTIME_DIR/build_oe4t_jetson_multi_platform_v67.runtime.sh"

log() { printf '\n[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }
die() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

[ -f "$BASE_SCRIPT" ] || die "Could not find v65 base script at: $BASE_SCRIPT. Put build_oe4t_jetson_multi_platform_v65.sh next to this v67 launcher, or set JETSON_BUILDER_V65_SCRIPT=/path/to/v65.sh."
command -v python3 >/dev/null 2>&1 || die "Missing required command: python3"
mkdir -p "$RUNTIME_DIR"

python3 - "$BASE_SCRIPT" "$RUNTIME_SCRIPT" <<'PY_PATCH_V67'
from pathlib import Path
import re
import sys

src = Path(sys.argv[1])
dst = Path(sys.argv[2])
text = src.read_text()

if 'build_oe4t_jetson_multi_platform_v65.sh' not in text:
    raise SystemExit('Base script does not look like v65; refusing to patch automatically.')

text = text.replace('build_oe4t_jetson_multi_platform_v65.sh', 'build_oe4t_jetson_multi_platform_v67.sh')
text = text.replace('Generated by build_oe4t_jetson_multi_platform_v65.sh', 'Generated by build_oe4t_jetson_multi_platform_v67.sh')
text = text.replace('generated by build_oe4t_jetson_multi_platform_v65.sh', 'generated by build_oe4t_jetson_multi_platform_v67.sh')
text = text.replace('tegra-flashtools-mkbootimg-wrapper-clean-v65', 'tegra-flashtools-flash-helper-wrapper-clean-v67')
text = text.replace('current v50 fix', 'current v67 fix')

v67_notes = '''# v67 notes:\n#   - Fixes Thor demo-image-full do_image_ext4 failure:\n#       mksparse: Exec format error\n#     v66 wrapped mkbootimg/mksparse only under ${bindir}/tegra-flash, but\n#     do_image_ext4 invokes mksparse directly from PATH. On Thor, that means\n#     ${bindir}/mksparse can remain the foreign-architecture NVIDIA payload.\n#   - Wraps mkbootimg and mksparse in both native install locations when present:\n#       ${bindir}/mkbootimg, ${bindir}/mksparse\n#       ${bindir}/tegra-flash/mkbootimg, ${bindir}/tegra-flash/mksparse\n#   - Leaves symlink helpers alone to avoid wrapper recursion; the actual target\n#     file is wrapped separately when it exists.\n#   - Uses a new v67 clean stamp and validates the populated native sysroot so\n#     stale unwrapped tegra-flashtools-native content is discarded.\n#\n'''
text = text.replace('# v65 notes:\n', v67_notes + '# v65 notes:\n', 1)

new_install = r'''install_tegra_flashtools_wrapper() {
    local distro_dir="$1" fix_layer="$2" platform="$3"
    local tegra_flashtools_base_glob="$distro_dir/layers/meta-tegra/recipes-bsp/tegra-binaries/tegra-flashtools_"*.bb
    local tegra_flashtools_native_glob="$distro_dir/layers/meta-tegra/recipes-bsp/tegra-binaries/tegra-flashtools-native_"*.bb
    local has_tegra_flashtools_base=0
    local has_tegra_flashtools_native=0

    compgen -G "$tegra_flashtools_base_glob" >/dev/null && has_tegra_flashtools_base=1
    compgen -G "$tegra_flashtools_native_glob" >/dev/null && has_tegra_flashtools_native=1

    if [ "$has_tegra_flashtools_base" = "1" ] || [ "$has_tegra_flashtools_native" = "1" ]; then
        mkdir -p "$fix_layer/recipes-bsp/tegra-flashtools/files"
        cat > "$fix_layer/recipes-bsp/tegra-flashtools/files/tegra-flash-helper-wrapper" <<'EOF_TEGRA_FLASH_HELPER_WRAPPER'
#!/bin/sh
set -u
self="$0"
tool_name="$(basename -- "$self")"
real="${self}.real"
[ -f "$real" ] || { echo "$tool_name wrapper error: missing payload $real" >&2; exit 126; }
chmod 0755 "$real" 2>/dev/null || true
tool_dir="$(CDPATH= cd -- "$(dirname -- "$self")" && pwd)"
native_bindir="$(CDPATH= cd -- "$tool_dir/.." && pwd)"
host_arch="$(uname -m 2>/dev/null || echo unknown)"
magic=""
if [ -x "$native_bindir/file" ]; then
    magic="$($native_bindir/file -L "$real" 2>/dev/null || true)"
elif command -v file >/dev/null 2>&1; then
    magic="$(file -L "$real" 2>/dev/null || true)"
fi
run_direct() { "$real" "$@"; rc=$?; case "$rc" in 126|127) return 1 ;; *) exit "$rc" ;; esac; }
exec_qemu() {
    qemu_name="$1"; shift
    for qemu in "$native_bindir/${qemu_name}" "$native_bindir/${qemu_name}-static" "/usr/bin/${qemu_name}" "/usr/bin/${qemu_name}-static" "${qemu_name}" "${qemu_name}-static"; do
        case "$qemu" in
            */*) [ -x "$qemu" ] && exec "$qemu" "$real" "$@" ;;
            *) command -v "$qemu" >/dev/null 2>&1 && exec "$qemu" "$real" "$@" ;;
        esac
    done
    return 1
}
case "$magic" in
    *"shell script"*|*"Python script"*|*"Perl script"*) exec "$real" "$@" ;;
    *"ELF"*"x86-64"*) case "$host_arch" in x86_64|amd64) exec "$real" "$@" ;; esac; exec_qemu qemu-x86_64 "$@" || true ;;
    *"ELF"*"80386"*|*"ELF"*"Intel 80386"*) case "$host_arch" in i386|i486|i586|i686) exec "$real" "$@" ;; esac; exec_qemu qemu-i386 "$@" || true ;;
    *"ELF"*"aarch64"*|*"ELF"*"ARM aarch64"*) case "$host_arch" in aarch64|arm64) exec "$real" "$@" ;; esac; exec_qemu qemu-aarch64 "$@" || true ;;
    *"ELF"*"ARM"*) case "$host_arch" in arm*|armhf) exec "$real" "$@" ;; esac; exec_qemu qemu-arm "$@" || true ;;
    *) run_direct "$@" || true; for qemu_name in qemu-aarch64 qemu-arm qemu-x86_64 qemu-i386; do exec_qemu "$qemu_name" "$@" || true; done ;;
esac
echo "$tool_name wrapper error: cannot execute $real on $host_arch" >&2
[ -n "$magic" ] && echo "$tool_name wrapper detected: $magic" >&2 || echo "$tool_name wrapper could not detect payload architecture; file(1) unavailable" >&2
exit 126
EOF_TEGRA_FLASH_HELPER_WRAPPER
        chmod 0755 "$fix_layer/recipes-bsp/tegra-flashtools/files/tegra-flash-helper-wrapper"
    fi

    if [ "$has_tegra_flashtools_base" = "1" ]; then
        cat > "$fix_layer/recipes-bsp/tegra-flashtools/tegra-flashtools_%.bbappend" <<'EOF_TEGRA_FLASHTOOLS_BASE'
DEPENDS:append:class-native = " qemu-native file-native"
JETSON_BUILDER_FIXDIR := "${THISDIR}"

jetson_builder_wrap_tegra_flash_helper_path() {
    helper_path="$1"
    helper_name="$(basename "$helper_path")"
    real_path="${helper_path}.real"
    wrapper_src="${JETSON_BUILDER_FIXDIR}/files/tegra-flash-helper-wrapper"
    [ -e "$helper_path" ] || return 0
    [ -f "$wrapper_src" ] || bbfatal "missing tegra flash helper wrapper at $wrapper_src"
    if [ -L "$helper_path" ]; then
        bbnote "jetson-builder v67: leaving symlinked tegra-flash helper ${helper_path} unchanged; target will be wrapped separately if present"
        return 0
    fi
    if [ -e "$real_path" ]; then
        rm -f "$helper_path"
    else
        mv "$helper_path" "$real_path"
    fi
    install -m 0755 "$wrapper_src" "$helper_path"
    chmod a+x "$real_path" || true
    bbnote "jetson-builder v67: wrapped tegra-flash helper ${helper_name}: ${helper_path} -> ${real_path}"
}

do_install:append:class-native() {
    for helper_name in mkbootimg mksparse; do
        jetson_builder_wrap_tegra_flash_helper_path "${D}${bindir}/tegra-flash/${helper_name}"
        jetson_builder_wrap_tegra_flash_helper_path "${D}${bindir}/${helper_name}"
    done
}
EOF_TEGRA_FLASHTOOLS_BASE
    else
        rm -f "$fix_layer/recipes-bsp/tegra-flashtools/tegra-flashtools_%.bbappend"
    fi

    if [ "$has_tegra_flashtools_native" = "1" ]; then
        cat > "$fix_layer/recipes-bsp/tegra-flashtools/tegra-flashtools-native_%.bbappend" <<'EOF_TEGRA_FLASHTOOLS_NATIVE'
DEPENDS:append = " qemu-native file-native"
JETSON_BUILDER_FIXDIR := "${THISDIR}"

jetson_builder_wrap_tegra_flash_helper_path() {
    helper_path="$1"
    helper_name="$(basename "$helper_path")"
    real_path="${helper_path}.real"
    wrapper_src="${JETSON_BUILDER_FIXDIR}/files/tegra-flash-helper-wrapper"
    [ -e "$helper_path" ] || return 0
    [ -f "$wrapper_src" ] || bbfatal "missing tegra flash helper wrapper at $wrapper_src"
    if [ -L "$helper_path" ]; then
        bbnote "jetson-builder v67: leaving symlinked tegra-flash helper ${helper_path} unchanged; target will be wrapped separately if present"
        return 0
    fi
    if [ -e "$real_path" ]; then
        rm -f "$helper_path"
    else
        mv "$helper_path" "$real_path"
    fi
    install -m 0755 "$wrapper_src" "$helper_path"
    chmod a+x "$real_path" || true
    bbnote "jetson-builder v67: wrapped tegra-flash helper ${helper_name}: ${helper_path} -> ${real_path}"
}

do_install:append() {
    for helper_name in mkbootimg mksparse; do
        jetson_builder_wrap_tegra_flash_helper_path "${D}${bindir}/tegra-flash/${helper_name}"
        jetson_builder_wrap_tegra_flash_helper_path "${D}${bindir}/${helper_name}"
    done
}
EOF_TEGRA_FLASHTOOLS_NATIVE
    else
        rm -f "$fix_layer/recipes-bsp/tegra-flashtools/tegra-flashtools-native_%.bbappend"
    fi

    if [ "$has_tegra_flashtools_base" != "1" ] && [ "$has_tegra_flashtools_native" != "1" ]; then
        rm -f "$fix_layer/recipes-bsp/tegra-flashtools/files/tegra-flash-helper-wrapper"
        log "Skipping tegra-flashtools helper wrapper for $platform; no matching recipe exists on this OE4T branch."
    fi
}'''

text, count = re.subn(r'install_tegra_flashtools_wrapper\(\) \{.*?\n\}\n\nensure_active_freeimage_pic_fix\(\)', new_install + '\n\nensure_active_freeimage_pic_fix(', text, count=1, flags=re.S)
if count != 1:
    raise SystemExit('Could not replace install_tegra_flashtools_wrapper() in v65 script.')

new_clean = r'''clean_tegra_flashtools_state_if_needed() {
    local platform="$1" distro_dir="$2" build_abs_dir="$3"
    [ "$platform" = "thor" ] || return 0
    local fix_layer="$distro_dir/layers/meta-jetson-builder-fixes"
    clean_recipe_state_if_fix_changed "$build_abs_dir" "tegra-flashtools-flash-helper-wrapper-clean-v67" "tegra-flashtools tegra-flashtools-native" \
        "$fix_layer/recipes-bsp/tegra-flashtools/tegra-flashtools_%.bbappend" \
        "$fix_layer/recipes-bsp/tegra-flashtools/tegra-flashtools-native_%.bbappend" \
        "$fix_layer/recipes-bsp/tegra-flashtools/files/tegra-flash-helper-wrapper"
    if [ -d "$build_abs_dir/tmp/sysroots-components" ]; then
        find "$build_abs_dir/tmp/sysroots-components" -type d -name tegra-flashtools-native -prune -exec rm -rf {} + 2>/dev/null || true
    fi
    if [ -d "$build_abs_dir/tmp/sstate-control" ]; then
        find "$build_abs_dir/tmp/sstate-control" -type f -name '*tegra-flashtools-native*populate_sysroot*' -delete 2>/dev/null || true
    fi
}

validate_tegra_flashtools_wrappers() {
    local platform="$1" build_abs_dir="${2:-}"
    [ "$platform" = "thor" ] || return 0
    log "Validating Thor v67 tegra-flashtools native wrappers for direct and tegra-flash mkbootimg/mksparse helpers"
    if ! bitbake -e tegra-flashtools-native >/tmp/jetson-builder-tegra-flashtools-native-v67-env.txt 2>/tmp/jetson-builder-tegra-flashtools-native-v67-env.err; then
        warn "tegra-flashtools-native is not active as a standalone recipe; trying tegra-flashtools native sysroot population via base recipe."
    else
        grep -q 'jetson_builder_wrap_tegra_flash_helper_path' /tmp/jetson-builder-tegra-flashtools-native-v67-env.txt || die "tegra-flashtools-native is active, but the v67 helper wrapper install hook is not visible in BitBake metadata."
    fi
    bitbake -c cleansstate tegra-flashtools-native || true
    bitbake -c populate_sysroot -f tegra-flashtools-native || bitbake -c populate_sysroot -f tegra-flashtools

    if [ -n "$build_abs_dir" ] && [ -d "$build_abs_dir/tmp/sysroots-components" ]; then
        local helper found=0 bad=0
        while IFS= read -r helper; do
            found=1
            if [ -L "$helper" ]; then
                continue
            fi
            if head -n 1 "$helper" 2>/dev/null | grep -q '/bin/sh' && grep -q 'wrapper error' "$helper" 2>/dev/null; then
                continue
            fi
            warn "Thor v67 validation: unwrapped tegra-flashtools helper remains in native sysroot: $helper"
            bad=1
        done < <(find "$build_abs_dir/tmp/sysroots-components" \( \
            -path '*/tegra-flashtools-native/*/usr/bin/mkbootimg' -o \
            -path '*/tegra-flashtools-native/*/usr/bin/mksparse' -o \
            -path '*/tegra-flashtools-native/*/usr/bin/tegra-flash/mkbootimg' -o \
            -path '*/tegra-flashtools-native/*/usr/bin/tegra-flash/mksparse' \
            \) \( -type f -o -type l \) -print 2>/dev/null || true)
        [ "$found" = "1" ] || warn "Thor v67 validation: no mkbootimg/mksparse helpers found under tegra-flashtools-native sysroots-components yet."
        [ "$bad" = "0" ] || die "Thor v67 tegra-flashtools validation failed; refusing to continue with unwrapped foreign-architecture helper payloads."
    fi
}'''

text, count = re.subn(r'clean_tegra_flashtools_state_if_needed\(\) \{.*?\n\}\n\nclean_freeimage_state_if_needed\(\)', new_clean + '\n\nclean_freeimage_state_if_needed(', text, count=1, flags=re.S)
if count != 1:
    raise SystemExit('Could not replace clean_tegra_flashtools_state_if_needed() in v65 script.')

old_call = 'clean_tegra_flashtools_state_if_needed "$platform" "$workspace/tegra-demo-distro" "$build_abs_dir"\n    prepare_and_validate_thor_cuda_native_sysroot'
new_call = 'clean_tegra_flashtools_state_if_needed "$platform" "$workspace/tegra-demo-distro" "$build_abs_dir"\n    validate_tegra_flashtools_wrappers "$platform" "$build_abs_dir"\n    prepare_and_validate_thor_cuda_native_sysroot'
text = text.replace(old_call, new_call, 1)

# The v65 script can contain old mkbootimg wrapper leftovers after replacement only
# in comments; keep generated runtime clearly executable.
dst.write_text(text)
dst.chmod(0o755)
PY_PATCH_V67

log "Created patched v67 runtime copy: $RUNTIME_SCRIPT"
exec "$RUNTIME_SCRIPT" "$@"
